name: Publish To Vscode
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm i

      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          REPO_URL: "${{ github.server_url }}/${{ github.repository }}"
          BRANCH: "${GITHUB_REF##*/}"
