name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm i

      - name: Run Tests
        run: npm run test